### ISSUE TITLE
Error spamming my console

### ISSUE THREAD

**Issue by IlPicasso** [geNAZt/CloudChat#81] opened 2014-03-29 23:00 UTC
http://pastebin.com/ksYJYn7Q

**Comment by geNAZt** [comment] 2014-03-30 12:17
Fixed in CloudChatBukkit 3.2.0

**Closed as completed by geNAZt** 2014-03-30 12:17 UTC

**Comment by IlPicasso** [comment] 2014-04-01 04:47
I am still getting the entity damage error
http://pastebin.com/8X7Bjp0G

**Comment by geNAZt** [comment] 2014-04-01 13:57
The problem is not complete. It just tells that there is a NPE but not where.
